# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-24 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_app', '0007_votetracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('Bug', 'Bug'), ('Feature', 'Feature')], default='Bug', max_length=7),
        ),
    ]
