# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-24 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_app', '0008_auto_20190424_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='issue',
            field=models.TextField(default='text', verbose_name='Short description of the issue:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(verbose_name='Full description of the issue:'),
        ),
    ]
