# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-24 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_app', '0009_auto_20190424_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='issue',
            field=models.CharField(max_length=100),
        ),
    ]
