# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-12 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name on Card')),
                ('address', models.CharField(max_length=200, verbose_name='Billing Address')),
                ('card', models.CharField(max_length=19, verbose_name='card_number')),
            ],
        ),
    ]
